name: IaC Validator
on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        default: './terraform'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ inputs.working_directory }}
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ${{ inputs.working_directory }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.working_directory }}
